branch-defaults:
  default:
    environment: CCAssignment3-env
environment-defaults:
  CCAssignment3-env:
    branch: null
    repository: null
global:
  application_name: CCAssignment3
  default_ec2_keyname: cc-assignment-3
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
